# Generated by Django 4.1.3 on 2022-11-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('total_price', models.FloatField()),
                ('payment_status', models.CharField(choices=[('success', 'Success'), ('due', 'Due')], max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
