# Generated by Django 4.1.3 on 2022-11-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trans_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
